title: Posts
description: My Personal Blog
author: Ankit Chandawala
github: https://github.com/nerandell
about: I'm a software engineer with experience in mobile, backend and distributed systems
disqus_shortname: nerandell
google_analytics: UA-68709154-1
avatar_url: https://www.gravatar.com/avatar/59d563cdddde473e2cfffc61f339428e
addthis_id: ra-5c2be88758074d7c

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/ankitchandawala"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ankitchandawala"
    - icon: fa-github
      link: "https://github.com/nerandell"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/938146/icoder"
    - icon: fa-instagram
      link: "https://www.instagram.com/ankitchandawala"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://nerandell.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

exclude:
  - .idea
