# Site settings
title: "Ankit Chandawala"
email: ankitchandawala@gmail.com
description: "Blog about work and hobbies"
baseurl: ""
url: "https://blog.ankitchandawala.com/"
title_description: "My name is Ankit and this is my website about everything I find time to write about. I currently work as a Software Engineer at Skyscanner where we are transforming the travel industry.

                    I currently live in London, and I love traveling, biking, hiking, and reading whenever I get time.

                    You can contact me by email at ankitchandawala /at/ gmail.com"
title_image: "https://www.gravatar.com/avatar/59d563cdddde473e2cfffc61f339428e?s=500&d=mm"
google_analytics: "UA-68709154-1"
disqus_account: nerandell
github_repository: https://github.com/nerandell/nerandell.github.io
addthis_id: ra-5c2be88758074d7c
post_limit: 5

# Social usernames/URLs
twitter_username: ankitchandawala
github_username:  nerandell
instagram_username: ankitchandawala
reddit_username:
linkedin_link: https://www.linkedin.com/in/ankitchandawala/
google_plus_link:
stackoverflow_link: https://stackoverflow.com/users/938146/icoder
xing_link:
facebook_link:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

plugins:
- jekyll-seo-tag
- jekyll-sitemap
